def sing_jiandanai():
    print("=================简单爱=====begin==========")
    print("说不上为什么 我变得很主动")
    print("若爱上一个人 什么都会值得去做")
    print("我想大声宣布 对你依依不舍")
    print("连隔壁邻居都猜到我现在的感受")
    print("河边的风 在吹着头发飘动")
    print("牵着你的手 一阵莫名感动")
    print("我想带你 回我的外婆家")
    print("一起看着日落 一直到我们都睡着")
    print("···")
    print("================简单爱======end===========")
    print(" ")

def sing_daoxiang():
    print("===============稻香=======begin==========")
    print("对这个世界如果你有太多的抱怨")
    print("跌倒了 就不能继续往前走")
    print("为什么 人要这么的脆弱 堕落")
    print("请你打开电视看看 多少人")
    print("为生命在努力勇敢的走下去")
    print("我们是不是该知足")
    print("···")
    print("==============稻香========end===========")
    print(" ")

sing_jiandanai()
sing_daoxiang()
sing_jiandanai()
sing_jiandanai()
sing_jiandanai()

